### ISSUE TITLE
Please upgrade the vue2-leaflet

### ISSUE THREAD

**Issue by sangdth** [jperelli/vue2-leaflet-markercluster#12]
Vue2-Leaflet has upgraded to v1.0.1 with some breaking changes. Cluster seems does not work after I've upgraded.

Thanks in advance.

**Comment by fdenzer** [comment]
Duplicate, as this is a work in progress under ticket number #10 .

That tickets seems to be about 1.0.1, so it is a misnomer as it has 1.0.0 in title?

**Comment by jperelli** [comment]
Closing in favor of https://github.com/jperelli/vue2-leaflet-markercluster/pull/10
