### ISSUE TITLE
How to access leaflet-markercluster's methods?

### ISSUE THREAD

**Issue by sangdth** [jperelli/vue2-leaflet-markercluster#14]
Hello @jperelli , this is not an issue, I'm just learning how to use your plugin.

If I'm not wrong, you are using [Leaflet.markercluster](https://github.com/Leaflet/Leaflet.markercluster#defaults) plugin, then how can I access their methods, in this case I want to call `refreshClusters()`

My component looks like this: 
```html
<v-marker-cluster
     ref="sourcesCluster"
     :options="clusterOptions"
>
     <l-marker
          v-for="(source, index) in currentLocationSources"
          ref="sourceMarkers"
     />          
</v-marker-cluster>
```
I've tried to run `this.$refs.sourcesCluster.refreshClusters()` but it said that is not a function.
Link: https://github.com/Leaflet/Leaflet.markercluster#refreshing-the-clusters-icon

Thank you.

**Comment by jperelli** [comment]
Good idea, I think it is not exposed, I'll take a look on doing it later today

**Comment by sangdth** [comment]
Thank you, I'm looking forward.

**Comment by jperelli** [comment]
You were close... you need to use `mapObject`, will add this to the documentation
```
this.$refs.sourcesCluster.mapObject.refreshClusters()
```
