### ISSUE TITLE
Error from calling L.MarkerClusterGroup after updating to 2.0.0

### ISSUE THREAD

**Issue by EmmanuelBeziat** [jperelli/vue2-leaflet-markercluster#15]
Hi,

Having just updated `vue2-leaflet` from 0.x.x to 1.0.2 (`vue2-leaflet-markercluster`  and `leaflet` dependencies are up to date too), I just ran into this error in console browser:

```
L.MarkerClusterGroup is not a constructor
```

My code hasn't change much, except for `the vue2-leaflet` breaking-changes that needed to be done.

Here's what it looks like:

```javascript
let V2L = {}
let V2LMarkerCluster = {}
let V2LTracksymbol = {}

if (process.browser) {
	L = require('leaflet')
	V2L = require('vue2-leaflet')
	V2LMarkerCluster = require('vue2-leaflet-markercluster')
}

export default {
	components: {
		'l-map': V2L.LMap,
		'l-marker': V2L.LMarker,
		'l-tilelayer': V2L.LTileLayer,
		'v-marker-cluster': V2LMarkerCluster
	}
// [...]
}
```
Except from the components names, there's no difference with before. I checked the doc here but I find nothing that I would have missed.

Any idea of what's happening?

Thanks!

**Comment by jperelli** [comment]
Try adding `leaflet.markercluster` to the list of requirements
```
if (process.browser) {
	L = require('leaflet')
        require('leaflet.markercluster')
	V2L = require('vue2-leaflet')
	V2LMarkerCluster = require('vue2-leaflet-markercluster')
}
```

**Comment by EmmanuelBeziat** [comment]
Hi,
Unfortunately, it has no effect…

**Comment by arenddeboer** [comment]
Did you find a solution ? I run into the same issue after updating.

**Comment by hponcede** [comment]
@arenddeboer which file should that be ?

**Comment by hponcede** [comment]
Thanks. Meanwhile, i've modified my `vue.config.js` : 
```
webpack = require('webpack')
module.exports = {
    configureWebpack: {
        plugins: [
            new webpack.ProvidePlugin({
              L: 'leaflet'
            })
          ]
    }
}
```

I still have other problems though, but with `leaflet.markercluster`, not the Vu2 componenent.

**Comment by jperelli** [comment]
I updated the package to v2.1.0, please try it again and let me know if this issue keeps appearing

**Comment by fdenzer** [comment]
For me, neither the package stack of

```
vue(-template-compiler) 2.6.6,
leaflet 1.4.0, vue2-leaflet 1.2.3, vue2-leaflet-markercluster 2.1.2
```

nor
```
vue @ 2.5.22
leaflet 1.3.4, vue2-leaflet 1.1.1, vue2-leaflet-markercluster 2.0.0
```

work any more (although the latter used to work for morethan a month).
Right now, on `npm 6.7` and `node 10.14.2` the error shown above about L.MarkerClusterGroup gets raised.

**Comment by zhanghoo** [comment]
> For me, neither of these package stacks work consistently, so I am having a hard time figuring out why the leaflet-part of my application breaks.
> 
> I am working on `npm 6.7.0` and `node 10.15.1` as of now.
> 
> ## Most current setup
> ```
> vue @ 2.5.22
> leaflet 1.3.4, vue2-leaflet 1.1.1, vue2-leaflet-markercluster 2.0.0
> ```
> The most current modules on the two unixoids produce the same results as OP described.
> 
> ## After downgrade to older versions of the JS-modules
> ```
> vue(-template-compiler) 2.6.6,
> leaflet 1.4.0, vue2-leaflet 1.2.3, vue2-leaflet-markercluster 2.1.2
> ```
> ### on a debian server w/ node 10:
> The error message is not literally as OP wrote, but:
> `Cannot read property 'markerClusterGroup' of undefined`
> where n.L is undefined.
> 
> ### My local machine
> (macOS) testing environment works like a charm.

Me too.

**Comment by jperelli** [comment]
Could you try now? I published v3.0.0

**Comment by zhanghoo** [comment]
When I clone your project. npm install, npm run example. It's working.
But when I install it (npm install --save vue2-leaflet-markercluster) in my other project (has install vue2-leaflet) and run dev. It's error ~~

[Vue warn]: Error in mounted hook: "TypeError: Cannot read property '_zoom' of undefined"
found in
---> <LMarker>
       <VMarkerCluster>
         <LMap>

Example.vue is right separately. But install in other isn't working.

**Comment by jperelli** [comment]
@zhanghoo could you tell me what packages do you have installed in your other project? Try installing `leaflet` and if it still doesn't work, try installing `leaflet.markercluster` also. Let me know if it works

**Comment by fdenzer** [comment]
> Could you try now? I published v3.0.0

Works for me (leaflet 1.4.0 vue2leaflet 1.2.3 vue2-leaflet-markercluster 3.0.0)
*but* for me some new cases of `cannot ready property parentnode of undefined` appeared (5 out of 400 markers/80ish markerclusters)
in leaflet src. It could be a previously masked error in my marker logic, though. No worries.

```javascript
// @function remove(el: HTMLElement)
// Removes `el` from its parent element
function remove(el) {
	var parent = el.parentNode;
/* [ etc .] */
```

**Comment by jperelli** [comment]
True. I'll need to setup the peer dependencies correctly. I'll do that

**Comment by zhanghoo** [comment]
I built new one. It's working. Thank you very much.
```
"leaflet": "^1.4.0",
"leaflet.markercluster": "^1.4.1",
"vue2-leaflet": "^2.0.2",
"vue2-leaflet-markercluster": "^3.0.0"
```

**Comment by AndreyNvk** [comment]
> 
> 
> When I clone your project. npm install, npm run example. It's working.
> But when I install it (npm install --save vue2-leaflet-markercluster) in my other project (has install vue2-leaflet) and run dev. It's error ~~
> 
> [Vue warn]: Error in mounted hook: "TypeError: Cannot read property '_zoom' of undefined"
> found in
> --->
> 
> Example.vue is right separately. But install in other isn't working.

Sorry for that, but I have the same problem as @zhanghoo had
The example.vue standalone works fine, but when it goes to my project it fails

I've tried to update the packages but it didn't help to solve the issue

Could you please tell what was the final remedy for this issue?

**Comment by jperelli** [comment]
@AndreyNvk the problem should be related to the packages' versions only. Please try updating to these https://github.com/jperelli/vue2-leaflet-markercluster/issues/15#issuecomment-469927508

**Comment by AndreyNvk** [comment]
@jperelli I've got exactly the same versions of the packages but it doesn't affect somehow the situation with the issue

I took a look on the Vue devtool and noticed that the order of elements is violated
I've got in the devtool the structure:
```
<LMap>
   <LIconDefault>
   <v-marker-cluster>
   <LTileLayer>
```
But in my vue component the `LTileLayer` goes first and after it the `v-marker-cluster`
I've changed the order of elements in the Example.vue and got errors in the console quite similar that I have in my project

Maybe this is the root cause of my problem

Do you have an idea why Vue violate the order of elements and how I can control it?

**Comment by zhanghoo** [comment]
I still don't know the reason. This demo is new one that runs  OK.  @AndreyNvk 
https://github.com/zhanghoo/vue-leaflet-demo.git

**Comment by jperelli** [comment]
@AndreyNvk can you share your code or make a project that has the error so we can reproduce it?

**Comment by AndreyNvk** [comment]
@jperelli yes, you can find the code which emits the error in [the repo](https://github.com/AndreyNvk/vue2-leaflet-markercluster-issue)

Is it ok that I continue to comment this issue or it's better to open a new one?

**Comment by jperelli** [comment]
@AndreyNvk It's ok here. I'm looking into your repo

**Comment by jperelli** [comment]
@AndreyNvk You never said that you were using rotatedmarker plugin. The problem is that that plugin is not made for vue2-leaflet version 2 https://github.com/mudin/vue2-leaflet-rotatedmarker, the upstream issue is that the rotatedmarker plugin is not compatible with ES6 modules declarations. See https://github.com/bbecquet/Leaflet.RotatedMarker/issues/11
I might create an es6 version of rotatedmarker or maybe create PRs to fix both repos, but I don't have the time right now. You might try contacting the original rotatedmarker developer...

**Comment by AndreyNvk** [comment]
@jperelli Yes, I've turned the rotadedmarker off and everything started to work smoothly

Julian, thank you for your detailed response you've really helped me to work it out

**Comment by wawagit** [comment]
> Did you find a solution ? I run into the same issue after updating.
> EDIT
> I solved my issue by moving `V2L = require('vue2-leaflet')` to a file that is included earlier in the app bootstrap routine. Because the actual import order of require() in webpack is not guaranteed, you can end up having the markercluster imported before leaflet, resulting in this error.

Thanks @arenddeboer ! I follow your move to fix the same issue in my react app using `leaflet-marker-cluster` and webpack.
