### ISSUE TITLE
Expanding a cluster mutates the lat-lng object

### ISSUE THREAD

**Issue by verdie-g** [jperelli/vue2-leaflet-markercluster#17]
Hi,

In the following code

```vue
<v-marker-cluster :options="clusterOptions" v-if="jobs.length !== 0">
    <l-marker
        v-for="job in jobs"
        v-if="job._geoloc !== null"
        :key="job.objectID"
        :lat-lng="job._geoloc">
        <l-popup :content="job.company_name + ': ' + job.name"></l-popup>
    </l-marker>
</v-marker-cluster>
```

expanding the cluster by clicking on a marker would mutate the object `job._geoloc` with the new position of the marker.

My workaround is the following:
```vue
:lat-lng="{ lat: job._geoloc.lat, lng: job._geoloc.lng }">
```
But it is annoying to make a copy of `_geoloc` for every marker.

Is this behaviour intentional ?

Thanks.

**Comment by jperelli** [comment]
Is this still happening in v3.0.0? there were some changes in the library

**Comment by jperelli** [comment]
If this issue persists, please don't hesitate in commenting and I'll reopen it
