### ISSUE TITLE
map has 3 markers,but show 2 markers

### ISSUE THREAD

**Issue by wuxiashuangji** [jperelli/vue2-leaflet-markercluster#18]
there are tree markers in the picture
![image](https://user-images.githubusercontent.com/21117027/40712353-15fbbb00-6430-11e8-9a91-ab5666df2235.png)

but it only show two markers

![image](https://user-images.githubusercontent.com/21117027/40712395-35be5aec-6430-11e8-87ca-07522467271a.png)

and i find three elements in  dom  , two markers is a same marker

![image](https://user-images.githubusercontent.com/21117027/40713070-c9522f6c-6431-11e8-8095-1110c908c706.png)

**Comment by wuxiashuangji** [comment]
i need your helps,this bug @jperelli

**Comment by wuxiashuangji** [comment]
I delete this and show normal 

![image](https://user-images.githubusercontent.com/21117027/40719097-ec6155e2-6444-11e8-940f-1a58ac443b81.png)

**Comment by VVNoodle** [comment]
I had the same problem and deleting that line works! Thanks for that!

**Comment by dreblen** [comment]
The problem seems to be related to vue2-leaflet, not to this package. I had this same problem with v1.0.2 of vue2-leaflet, but it seems to be fixed in v1.1.1 and newer, so the workaround of removing the line from the leaflet.markercluster package is no longer necessary.

**Comment by jperelli** [comment]
ok, I'll try updating the package, thanks!

**Comment by jperelli** [comment]
I updated the dependencies and published to npm, you can upgrade now to vue2-leaflet-markercluster@2.1.0, I tested it and the issue got fixed.
Please also test it if you can and let me know if there is any problem.
Sorry for the delay, merry christmas :santa:

**Comment by jperelli** [comment]
Seems that this is fixed, closing
