### ISSUE TITLE
Work with Vue2Leaflet.LImageOverlay

### ISSUE THREAD

**Issue by nik-el** [jperelli/vue2-leaflet-markercluster#19]
Hello!
Thans for plugin)

I have problem, when i use ImageOverlay instead of TileLayer.

In example.vue

```
<template>
  <v-map :zoom=10 :center="initialLocation">
    <v-icondefault></v-icondefault>
    <!--<v-tilelayer url="http://{s}.tile.osm.org/{z}/{x}/{y}.png"></v-tilelayer>-->
    <l-image-overlay :url="url" :bounds="bounds"></v-image-overlay>
    <v-marker-cluster>
      <v-marker v-for="l in locations" :key="l.id" :lat-lng="l.latlng">
        <v-popup :content="l.text"></v-popup>
      </v-marker>
    </v-marker-cluster>
  </v-map>
</template>
```

<img width="1274" alt="2018-07-11 10 51 50" src="https://user-images.githubusercontent.com/16726703/42558141-068c204e-84f9-11e8-8362-def28d998390.png">

**Comment by nik-el** [comment]
i found solution
in this [post](https://github.com/Leaflet/Leaflet.markercluster/issues/611#issuecomment-277670244)

just add
` map._layersMaxZoom = `

sorry that bothered

**Comment by jperelli** [comment]
wow, weird... thanks for posting the solution!
