### ISSUE TITLE
Map doesn't update when the options changes

### ISSUE THREAD

**Issue by dramaking** [jperelli/vue2-leaflet-markercluster#2]
I am trying to give users the option to toggle the cluster by using "disableClusteringAtZoom" option:
```
<v-marker-cluster :options="clusterOptions">
      <v-marker v-for="(marker, index) in assetMarkers" :key="index" :lat-lng="marker.position" :icon="marker.icon"></v-marker>
</v-marker-cluster>
```
then return the clusterOptions an object in the computed property.

But the map doesn't toggle the cluster unless I reload the page.

So I ended up doing this
```
<template v-if="isClusterOn">
        <v-marker-cluster>
          <v-marker v-for="(marker, index) in assetMarkers" :key="index" :lat-lng="marker.position" :icon="marker.icon"></v-marker>
        </v-marker-cluster>
</template>
<template v-else>
        <v-marker v-for="(marker, index) in assetMarkers" :key="index" :lat-lng="marker.position" :icon="marker.icon"></v-marker>
      </template>
```
Can we bind the cluster options to the map so that it can be updated immedietely?

**Comment by jperelli** [comment]
Nice one, let me see if I can do something about this. Also, any pull request to solve this is welcome

**Comment by jperelli** [comment]
@dramaking I fixed it, but I don't know why it didn't work with watch deep:true, so you'll need to create a new options object every time you change an option, something like this:

    newOptions = Object.assign({}, oldOptions, {opt: val})
