### ISSUE TITLE
Can't connect CSS styles

### ISSUE THREAD

**Issue by dzarezenko** [jperelli/vue2-leaflet-markercluster#24]
When I am trying to connect CSS styles like described in the README.md
```
@import "~leaflet.markercluster/dist/MarkerCluster.css";
@import "~leaflet.markercluster/dist/MarkerCluster.Default.css";
```
I received this error `Error: Can't resolve '~leaflet.markercluster/dist/MarkerCluster.css'`

npm module is installed and these CSS files are exist

**Comment by jperelli** [comment]
This seems a webpack/rollup/whathever related error. Maybe it's related to the tilde "~" not being resolved
