### ISSUE TITLE
Problems using vue2-leaflet-markercluster in Nuxt

### ISSUE THREAD

**Issue by pablocattaneo** [jperelli/vue2-leaflet-markercluster#27]
Using nuxt-leaflet module I can set an use alot of the component list: https://github.com/schlunsen/nuxt-leaflet/blob/master/lib/templates/plugin.js like l-marker, l-map, l-tile-layer, but my project also require to use https://github.com/jperelli/vue2-leaflet-markercluster

What is the correct way to implement it in Nuxt? 

I try this:

Create a plugins: vue2-leaflet-markercluster.js
```
import Vue from "vue";
import Vue2LeafletMarkerCluster from "vue2-leaflet-markercluster";
Vue.component("v-marker-cluster", Vue2LeafletMarkerCluster);
Vue.use(Vue2LeafletMarkerCluster);
```

Then set it in nuxt.config.js

```
  plugins: [
    { src: "~/plugins/vue2-leaflet-markercluster.js", mode: "client" }
  ],
  modules: [
    "@nuxtjs/axios",
    "@nuxtjs/pwa",
    "@nuxtjs/sitemap",
    "nuxt-leaflet"
  ],
```
and implemented in a page:

<template>
  <div id="map-wrap" style="height: 100vh">
    <no-ssr>
      <l-map :zoom="zoom" :center="[latitude, longitude]" :options="options">
        <l-tile-layer :url="tileLayer"></l-tile-layer>
        <v-marker-cluster>
          <l-marker
            v-for="(marker, index) in markers"
            :key="index"
            :lat-lng="[marker.markerLat, marker.markerpLng]"
          ></l-marker>
        </v-marker-cluster>
      </l-map>
    </no-ssr>
  </div>
</template>

```
<script>
export default {
  head() {
    return {
      link: [
        {
          rel: "stylesheet",
          href:
            "https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.4.1/MarkerCluster.Default.css"
        },
        {
          rel: "stylesheet",
          href:
            "https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.4.1/MarkerCluster.css"
        }
      ]
    };
  },
  data() {
    return {
      tileLayer: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
      latitude: -34.477518,
      longitude: -58.496699,
      zoom: 10,
      options: { scrollWheelZoom: false },
      markers: [
        { markerLat: "-34.477518", markerpLng: "-58.496699" },
        { markerLat: "-34.808505", markerpLng: "-58.402064" },
        { markerLat: "-34.796024", markerpLng: "-58.388854" },
        { markerLat: "-34.678739", markerpLng: "-58.338006" },
        { markerLat: "-34.678269", markerpLng: "-58.367989" },
       ...
      ]
    };
  },
  mounted() {
    // eslint-disable-next-line no-console
    console.log(this.$L);
  }
};
</script>
```

The output:

![image](https://user-images.githubusercontent.com/11772956/55165315-f79a6a80-514b-11e9-965f-e1bea1c7d8c6.png)

It look great, the problem happens when I click over a cluster it give me this error:

> Uncaught TypeError: Cannot read property '_removePath' of undefined

![image](https://user-images.githubusercontent.com/11772956/55165442-2f091700-514c-11e9-9e34-9d3677613794.png)

![image](https://user-images.githubusercontent.com/11772956/55165707-a50d7e00-514c-11e9-98c2-275c97d44af3.png)

**Comment by pablocattaneo** [comment]
Hi @nelsonlarocca I solved the problem in that way:

1- I created a plugin in the plugins directory I named it vue2-leaflet-markercluster.js. The code:
```javascript
import Vue from "vue";
import * as L from "leaflet";
import Vue2LeafletMarkerCluster from "vue2-leaflet-markercluster";
Vue.component("v-marker-cluster", Vue2LeafletMarkerCluster);

const LeafletPlugin = {
  install(Vue) {
    // Expose Leaflet
    Vue.prototype.$L = L;
  }
};

Vue.use(LeafletPlugin);
```

2- I added plugin in /nuxt.config.js
![image](https://user-images.githubusercontent.com/11772956/64069901-ae82a100-cc2a-11e9-993b-31635391a9b6.png)

Hope it can help you.

**Comment by nelsonlarocca** [comment]
Thanks a lot Pablo !
Would you mind sharing just some code enclosed inside the <template> tag just to check that out ?
Just any simple code to complete what you published to get any clue about what I'm doing wrong

Thanks in advance.
Regards,
Nelson

**Comment by nelsonlarocca** [comment]
Thanks Pablo, it worked out !!!

**Comment by pablocattaneo** [comment]
Great @nelsonlarocca !! Glad to hear that!!

**Comment by dpr989** [comment]
Awesome! Should close this issue? @pablocattaneo

**Comment by jperelli** [comment]
Closing issue. Thanks @pablocattaneo.
Also as an alternative, try upgrading to latest version, it works very differently on exposing the global.L variable

**Comment by pablocattaneo** [comment]
> Awesome! Should close this issue? @pablocattaneo

Yes @dpr989 you can close it!
