### ISSUE TITLE
Marker cluster click

### ISSUE THREAD

**Issue by verediongzon** [jperelli/vue2-leaflet-markercluster#6]
Does this module extends the clusterclick event? If yes, how do I do it? if no, do you have any recommendation to do it? I wanted to achieve getting the mid point of clicked clustered coordinates.

I checked this one on the leaflet doc, the click event:
https://github.com/Leaflet/Leaflet.markercluster

**Comment by jperelli** [comment]
@verediongzon I'm working on this one right now, expect to have it done in a couple of hours. Sorry for the delay, hope that helps someone when finished and thanks for the report :)

**Comment by jperelli** [comment]
@verediongzon Done and published as version 1.3.0 in npm

**Comment by verediongzon** [comment]
@jperelli Hi thank you for the enhancement. This is a very useful module.
