### ISSUE TITLE
Problem with new version of Vue2Leaflet

### ISSUE THREAD

**Issue by mits87** [jperelli/vue2-leaflet-markercluster#9]
Hi, 

vue2-leflet-markercluster not working with Vue2Leaflet "v1.x.x" package.
[https://www.dropbox.com/s/7twy2dv876es396/Screenshot%202018-03-27%2020.56.30.png?dl=0](https://www.dropbox.com/s/7twy2dv876es396/Screenshot%202018-03-27%2020.56.30.png?dl=0)

Could you fix it?
Thx

**Comment by naderio** [comment]
@jperelli @mits87 check PR #10, work in progress...

**Comment by jperelli** [comment]
done in version 2.0.0 thanks to @naderio
